// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUaqyxyNlqlTgD_h42isrnvDWc4fehrw8',
    appId: '1:1049232613660:web:0b43323c66cc522a011ad9',
    messagingSenderId: '1049232613660',
    projectId: 'multi-store-4bfec',
    authDomain: 'multi-store-4bfec.firebaseapp.com',
    storageBucket: 'multi-store-4bfec.appspot.com',
    measurementId: 'G-4W10MJK2DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMT8uGpj8cfWDt6BuueWMNRxFBOl5rX6c',
    appId: '1:1049232613660:android:f0a459531e00f6da011ad9',
    messagingSenderId: '1049232613660',
    projectId: 'multi-store-4bfec',
    storageBucket: 'multi-store-4bfec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX1q6II8GH6HVEkwMQJvgKmfJkmZUsIqg',
    appId: '1:1049232613660:ios:56835361f7ff935e011ad9',
    messagingSenderId: '1049232613660',
    projectId: 'multi-store-4bfec',
    storageBucket: 'multi-store-4bfec.appspot.com',
    iosBundleId: 'com.example.multiStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX1q6II8GH6HVEkwMQJvgKmfJkmZUsIqg',
    appId: '1:1049232613660:ios:fa6660df3ff61fef011ad9',
    messagingSenderId: '1049232613660',
    projectId: 'multi-store-4bfec',
    storageBucket: 'multi-store-4bfec.appspot.com',
    iosBundleId: 'com.example.multiStore.RunnerTests',
  );
}
